import Navbar from '@/components/navbar/Navbar'
import '@/styles/Global.css'
import { Lora } from 'next/font/google'
import Head from 'next/head'


const fuente = Lora({
    weight: '400', 
    subsets: ['latin']
})

export default function App({ Component, pageProps }) {
    return (
        <>
        <Head>
            <title>NearMe</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={fuente.className}>
            <Navbar/>
        <Component {...pageProps} />
        </main>
        </>
    )
}
